apiVersion: v1
kind: Namespace
metadata:
  name: team-a
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-b
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: team-b
spec:
  containers:
  - name: curl-container
    image: curlimages/curl
    command: ["/bin/sleep", "3650d"] # 使 Pod 保持運行
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice-v1
  namespace: team-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myservice
      version: v1
  template:
    metadata:
      labels:
        app: myservice
        version: v1
    spec:
      containers:
        - name: myservice
          image:  nginx
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myservice
  namespace: team-a
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: myservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice-v2
  namespace: team-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myservice
      version: v2
  template:
    metadata:
      labels:
        app: myservice
        version: v2
    spec:
      containers:
        - name: myservice
          image: kong/httpbin
          ports:
            - containerPort: 80
---
# 這個 Service 同時選擇了 v1 和 v2
apiVersion: v1
kind: Service
metadata:
  name: myservice
  namespace: team-a
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: myservice
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myservice
  namespace: team-a
spec:
  hosts:
    - myservice
  http:
    - route:
        - destination:
            host: myservice
            subset: v2
  exportTo:
    - "."

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: myservice
  namespace: team-a
spec:
  host: myservice
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
  exportTo:
    - "."